#!/usr/bin/env python3

import os
import sys
import subprocess

import configparser

SYNC_CONFIG_FILE = '.syncconfig'
SYNC_IGNORE_FILE = '.syncignore'

s3_bucket = None

def parse_config():
    config = configparser.ConfigParser()
    config.read(os.path.join(os.getcwd(), SYNC_CONFIG_FILE))
    global s3_bucket
    s3_bucket = config.get('s3', 'bucket')

def get_excludes():
    excludes = []
    root = os.getcwd()
    for root, subdirs, files in os.walk(root):
        if SYNC_IGNORE_FILE in files:
            with open(os.path.join(root, SYNC_IGNORE_FILE), 'r') as f:
                lines = list(f)
            for line in lines:
                excludes.append(os.path.join(root, line).rstrip())
    return excludes

def dryrun(excludes):
    command = ['aws', 's3', 'sync', '--dryrun', '--delete']
    for exclude in excludes:
        command.append('--exclude')
        command.append(exclude)
    command.append(os.getcwd())
    command.append('s3://andybug')

    cp = subprocess.run(command, stdout=subprocess.PIPE)
    for line in cp.stdout.splitlines():
        print(str(line))

if __name__ == '__main__':
    parse_config()
    excludes = get_excludes()
    dryrun(excludes)
